// Code generated by protoc-gen-go. DO NOT EDIT.
// source: beer.proto

/*
Package beer is a generated protocol buffer package.

It is generated from these files:
	beer.proto

It has these top-level messages:
	Empty
	Beer
	Cellar
	BeerCellar
*/
package beer

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Beer struct {
	Id        int64  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	DrinkDate int64  `protobuf:"varint,2,opt,name=drink_date,json=drinkDate" json:"drink_date,omitempty"`
	Size      string `protobuf:"bytes,3,opt,name=size" json:"size,omitempty"`
}

func (m *Beer) Reset()                    { *m = Beer{} }
func (m *Beer) String() string            { return proto.CompactTextString(m) }
func (*Beer) ProtoMessage()               {}
func (*Beer) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Beer) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Beer) GetDrinkDate() int64 {
	if m != nil {
		return m.DrinkDate
	}
	return 0
}

func (m *Beer) GetSize() string {
	if m != nil {
		return m.Size
	}
	return ""
}

type Cellar struct {
	Name  string  `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Beers []*Beer `protobuf:"bytes,2,rep,name=beers" json:"beers,omitempty"`
}

func (m *Cellar) Reset()                    { *m = Cellar{} }
func (m *Cellar) String() string            { return proto.CompactTextString(m) }
func (*Cellar) ProtoMessage()               {}
func (*Cellar) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Cellar) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Cellar) GetBeers() []*Beer {
	if m != nil {
		return m.Beers
	}
	return nil
}

type BeerCellar struct {
	Name          string    `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	SyncTime      int64     `protobuf:"varint,2,opt,name=syncTime" json:"syncTime,omitempty"`
	UntappdKey    string    `protobuf:"bytes,3,opt,name=untappdKey" json:"untappdKey,omitempty"`
	UntappdSecret string    `protobuf:"bytes,4,opt,name=untappdSecret" json:"untappdSecret,omitempty"`
	Cellars       []*Cellar `protobuf:"bytes,5,rep,name=cellars" json:"cellars,omitempty"`
}

func (m *BeerCellar) Reset()                    { *m = BeerCellar{} }
func (m *BeerCellar) String() string            { return proto.CompactTextString(m) }
func (*BeerCellar) ProtoMessage()               {}
func (*BeerCellar) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *BeerCellar) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *BeerCellar) GetSyncTime() int64 {
	if m != nil {
		return m.SyncTime
	}
	return 0
}

func (m *BeerCellar) GetUntappdKey() string {
	if m != nil {
		return m.UntappdKey
	}
	return ""
}

func (m *BeerCellar) GetUntappdSecret() string {
	if m != nil {
		return m.UntappdSecret
	}
	return ""
}

func (m *BeerCellar) GetCellars() []*Cellar {
	if m != nil {
		return m.Cellars
	}
	return nil
}

func init() {
	proto.RegisterType((*Empty)(nil), "beer.Empty")
	proto.RegisterType((*Beer)(nil), "beer.Beer")
	proto.RegisterType((*Cellar)(nil), "beer.Cellar")
	proto.RegisterType((*BeerCellar)(nil), "beer.BeerCellar")
}

func init() { proto.RegisterFile("beer.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 236 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0x3b, 0x4f, 0xc3, 0x30,
	0x14, 0x85, 0x95, 0x57, 0x4b, 0x0e, 0x8f, 0xe1, 0x4e, 0x16, 0x12, 0x28, 0x8a, 0x10, 0xca, 0xd4,
	0x01, 0x76, 0x06, 0x1e, 0x03, 0x62, 0x33, 0xec, 0xc8, 0x8d, 0xef, 0x60, 0xd1, 0xa4, 0x91, 0x63,
	0x86, 0xf0, 0x93, 0xf8, 0x95, 0xc8, 0x37, 0x2d, 0x82, 0xa5, 0xdb, 0x79, 0x58, 0xf7, 0x7c, 0x32,
	0xb0, 0x66, 0xf6, 0xab, 0xc1, 0x6f, 0xc3, 0x96, 0xf2, 0xa8, 0xeb, 0x25, 0x8a, 0xa7, 0x6e, 0x08,
	0x53, 0xfd, 0x8c, 0xfc, 0x9e, 0xd9, 0xd3, 0x19, 0x52, 0x67, 0x55, 0x52, 0x25, 0x4d, 0xa6, 0x53,
	0x67, 0xe9, 0x02, 0xb0, 0xde, 0xf5, 0x1f, 0xef, 0xd6, 0x04, 0x56, 0xa9, 0xe4, 0xa5, 0x24, 0x8f,
	0x26, 0x30, 0x11, 0xf2, 0xd1, 0x7d, 0xb1, 0xca, 0xaa, 0xa4, 0x29, 0xb5, 0xe8, 0xfa, 0x0e, 0x8b,
	0x07, 0xde, 0x6c, 0x8c, 0x8f, 0x6d, 0x6f, 0x3a, 0x96, 0x73, 0xa5, 0x16, 0x4d, 0x15, 0x8a, 0xb8,
	0x3c, 0xaa, 0xb4, 0xca, 0x9a, 0xe3, 0x1b, 0xac, 0x84, 0x29, 0x6e, 0xeb, 0xb9, 0xa8, 0xbf, 0x13,
	0x20, 0xfa, 0x03, 0x47, 0xce, 0x71, 0x34, 0x4e, 0x7d, 0xfb, 0xe6, 0xba, 0x3d, 0xd3, 0xaf, 0xa7,
	0x4b, 0xe0, 0xb3, 0x0f, 0x66, 0x18, 0xec, 0x0b, 0x4f, 0x3b, 0xb0, 0x3f, 0x09, 0x5d, 0xe1, 0x74,
	0xe7, 0x5e, 0xb9, 0xf5, 0x1c, 0x54, 0x2e, 0x4f, 0xfe, 0x87, 0x74, 0x8d, 0x65, 0x2b, 0xfb, 0xa3,
	0x2a, 0x04, 0xf4, 0x64, 0x06, 0x9d, 0xa1, 0xf4, 0xbe, 0x5c, 0x2f, 0xe4, 0x37, 0x6f, 0x7f, 0x02,
	0x00, 0x00, 0xff, 0xff, 0x92, 0xb5, 0xf0, 0x3b, 0x5b, 0x01, 0x00, 0x00,
}
