// Code generated by protoc-gen-go. DO NOT EDIT.
// source: beer.proto

/*
Package beer is a generated protocol buffer package.

It is generated from these files:
	beer.proto

It has these top-level messages:
	Empty
	Beer
*/
package beer

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Beer struct {
	Id        int64  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	DrinkDate int64  `protobuf:"varint,2,opt,name=drink_date,json=drinkDate" json:"drink_date,omitempty"`
	Size      string `protobuf:"bytes,3,opt,name=size" json:"size,omitempty"`
}

func (m *Beer) Reset()                    { *m = Beer{} }
func (m *Beer) String() string            { return proto.CompactTextString(m) }
func (*Beer) ProtoMessage()               {}
func (*Beer) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Beer) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Beer) GetDrinkDate() int64 {
	if m != nil {
		return m.DrinkDate
	}
	return 0
}

func (m *Beer) GetSize() string {
	if m != nil {
		return m.Size
	}
	return ""
}

func init() {
	proto.RegisterType((*Empty)(nil), "beer.Empty")
	proto.RegisterType((*Beer)(nil), "beer.Beer")
}

func init() { proto.RegisterFile("beer.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 119 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0x4a, 0x4d, 0x2d,
	0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x01, 0xb1, 0x95, 0xd8, 0xb9, 0x58, 0x5d, 0x73,
	0x0b, 0x4a, 0x2a, 0x95, 0x3c, 0xb9, 0x58, 0x9c, 0x52, 0x53, 0x8b, 0x84, 0xf8, 0xb8, 0x98, 0x32,
	0x53, 0x24, 0x18, 0x15, 0x18, 0x35, 0x98, 0x83, 0x98, 0x32, 0x53, 0x84, 0x64, 0xb9, 0xb8, 0x52,
	0x8a, 0x32, 0xf3, 0xb2, 0xe3, 0x53, 0x12, 0x4b, 0x52, 0x25, 0x98, 0xc0, 0xe2, 0x9c, 0x60, 0x11,
	0x97, 0xc4, 0x92, 0x54, 0x21, 0x21, 0x2e, 0x96, 0xe2, 0xcc, 0xaa, 0x54, 0x09, 0x66, 0x05, 0x46,
	0x0d, 0xce, 0x20, 0x30, 0x3b, 0x89, 0x0d, 0x6c, 0x81, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0xee,
	0x35, 0x25, 0x49, 0x6e, 0x00, 0x00, 0x00,
}
